# Generated by Django 3.1.1 on 2020-12-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20201227_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='job_pics'),
        ),
    ]
