# Generated by Django 3.1.1 on 2020-12-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_apply',
            field=models.BooleanField(blank=True, null=True, verbose_name='Apply'),
        ),
    ]
