# Generated by Django 3.1.1 on 2021-01-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_auto_20201227_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_published',
            field=models.BooleanField(blank=True, null=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
