# Generated by Django 3.1.1 on 2021-01-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_auto_20210112_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
