# Generated by Django 3.1.1 on 2021-01-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201227_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='voter_id_pics', verbose_name='Voter ID Image'),
        ),
    ]
